# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    dishes:
      uri_prefix: upload/images/
      upload_destination: '%kernel.project_dir%/public/upload/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true